# Generated by Django 5.2.8 on 2026-01-11 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('registration_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'Aircrafts',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'db_table': 'Airport',
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('crew_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Crew',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('nationality', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
            ],
            options={
                'db_table': 'Passengers',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_number', models.CharField(max_length=10)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('aircraft', models.ForeignKey(db_column='aircraft_id', on_delete=django.db.models.deletion.PROTECT, to='core.aircraft')),
                ('airport', models.ForeignKey(db_column='airport_id', on_delete=django.db.models.deletion.PROTECT, to='core.airport')),
            ],
            options={
                'db_table': 'Flights',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField()),
                ('seat_number', models.CharField(max_length=10)),
                ('travel_class', models.CharField(db_column='class', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight', models.ForeignKey(db_column='flight_id', on_delete=django.db.models.deletion.CASCADE, to='core.flight')),
                ('passenger', models.ForeignKey(db_column='passenger_id', on_delete=django.db.models.deletion.CASCADE, to='core.passenger')),
            ],
            options={
                'db_table': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=50)),
                ('issue_date', models.DateTimeField()),
                ('payment_status', models.CharField(max_length=30)),
                ('booking', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
            ],
            options={
                'db_table': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='FlightCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_role', models.CharField(max_length=50)),
                ('crew', models.ForeignKey(db_column='crew_id', on_delete=django.db.models.deletion.CASCADE, to='core.crew')),
                ('flight', models.ForeignKey(db_column='flight_id', on_delete=django.db.models.deletion.CASCADE, to='core.flight')),
            ],
            options={
                'db_table': 'Flight_Crew',
                'unique_together': {('flight', 'crew')},
            },
        ),
    ]
